DROP DATABASE IF EXISTS hangmanDB;
CREATE DATABASE hangmanDB;

USE hangmanDB;

CREATE TABLE game(
id INT PRIMARY KEY AUTO_INCREMENT,
answer VARCHAR(200) NOT NULL,
inProgress BOOL NOT NULL DEFAULT TRUE,
wrongGuess INT DEFAULT 0);

CREATE TABLE round(
id INT PRIMARY KEY AUTO_INCREMENT,
guess VARCHAR(10) NOT NULL,
currentAnswer VARCHAR(200),
gameId INT,
FOREIGN KEY fk_game (gameId) REFERENCES game(id)
);